#
# - Find libiptext
# Find the native LIBIPTEXT includes and library
#
#  LIBIPTEXT_INCLUDE_DIRS - where to find libiptc.h, etc.
#  LIBIPTEXT_LIBRARIES    - List of libraries when using libiptext.
#  LIBIPTEXT_FOUND        - True if libiptext found.


SET(LIBIPTEXT_NAMES libiptext.so)
FIND_LIBRARY(LIBIPTEXT_LIBRARY NAMES ${LIBIPTEXT_NAMES})

# handle the QUIETLY and REQUIRED arguments and set LIBIPTEXT_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBIPTEXT DEFAULT_MSG LIBIPTEXT_LIBRARY)

IF(LIBIPTEXT_FOUND)
  MESSAGE("LIBXTABLE FOUND")
  SET( LIBIPTEXT_LIBRARIES ${LIBIPTEXT_LIBRARY} )
ELSE(LIBIPTEXT_FOUND)
  SET( LIBIPTEXT_LIBRARIES )
  SET( LIBIPTEXT_INCLUDE_DIRS )
ENDIF(LIBIPTEXT_FOUND)

MARK_AS_ADVANCED( LIBIPTEXT_LIBRARIES LIBIPTEXT_INCLUDE_DIRS)
