#
# - Find libip4tc
# Find the native LIBIP4TC includes and library
#
#  LIBIP4TC_INCLUDE_DIRS - where to find libiptc.h, etc.
#  LIBIP4TC_LIBRARIES    - List of libraries when using libip4tc.
#  LIBIP4TC_FOUND        - True if libip4tc found.


IF (LIBIP4TC_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(LIBIP4TC_FIND_QUIETLY TRUE)
ENDIF (LIBIP4TC_INCLUDE_DIRS)

FIND_PATH(LIBIP4TC_INCLUDE_DIR libiptc.h PATH_SUFFIXES libiptc)
SET(LIBIP4TC_NAMES ip4tc.so libip4tc.so)
FIND_LIBRARY(LIBIP4TC_LIBRARY NAMES ${LIBIP4TC_NAMES})

# handle the QUIETLY and REQUIRED arguments and set LIBIP4TC_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBIP4TC DEFAULT_MSG LIBIP4TC_LIBRARY LIBIP4TC_INCLUDE_DIR)

IF(LIBIP4TC_FOUND)
  SET( LIBIP4TC_LIBRARIES ${LIBIP4TC_LIBRARY} )
  SET( LIBIP4TC_INCLUDE_DIRS ${LIBIP4TC_INCLUDE_DIR} )
ELSE(LIBIP4TC_FOUND)
  SET( LIBIP4TC_LIBRARIES )
  SET( LIBIP4TC_INCLUDE_DIRS )
ENDIF(LIBIP4TC_FOUND)

MARK_AS_ADVANCED( LIBIP4TC_LIBRARIES LIBIP4TC_INCLUDE_DIRS )

