#
# - Find NFQUEUE
# Find the native userspace rcu includes and library
#
#  NFQUEUE_INCLUDE_DIRS - where to find NFQUEUE.h, etc.
#  NFQUEUE_LIBRARIES    - List of libraries when using NFQUEUE
#  NFQUEUE_FOUND        - True if NFQUEUE found.


IF (NFQUEUE_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(NFQUEUE_FIND_QUIETLY TRUE)
ENDIF (NFQUEUE_INCLUDE_DIRS)

FIND_PATH(NFQUEUE_INCLUDE_DIR libnetfilter_queue/libnetfilter_queue.h)

FIND_LIBRARY(NFNETLINK_LIBRARY NAMES nfnetlink )
FIND_LIBRARY(NETFILTER_QUEUE_LIBRARY NAMES netfilter_queue )
FIND_LIBRARY(NETFILTER_CONNTRACK_LIBRARY NAMES netfilter_conntrack )
FIND_LIBRARY(MNL_LIBRARY NAMES mnl )

# handle the QUIETLY and REQUIRED arguments and set NFQUEUE_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NFQUEUE DEFAULT_MSG NFNETLINK_LIBRARY NFQUEUE_INCLUDE_DIR)

IF(NFQUEUE_FOUND)
  SET( NFQUEUE_LIBRARIES ${NFNETLINK_LIBRARY} ${NETFILTER_QUEUE_LIBRARY} ${NETFILTER_CONNTRACK_LIBRARY} ${MNL_LIBRARY})
  SET( NFQUEUE_INCLUDE_DIRS ${NFQUEUE_INCLUDE_DIR} )
ELSE(NFQUEUE_FOUND)
  SET( NFQUEUE_LIBRARIES )
  SET( NFQUEUE_INCLUDE_DIRS )
ENDIF(NFQUEUE_FOUND)

MARK_AS_ADVANCED( NFQUEUE_LIBRARIES NFQUEUE_INCLUDE_DIRS )
